repos:
- repo: local
  hooks:
    - id: lint
      name: Run linter
      entry: make lint
      language: system
      types: [python]
      require_serial: true
    - id: test
      name: Run tests
      entry: make test
      language: system
      types: [python]
      require_serial: true
