files: 'raster_loader\/'
repos:
    - repo: https://github.com/psf/black
      rev: 22.3.0
      hooks:
          - id: black
            language_version: python3
    - repo: https://github.com/pycqa/flake8
      rev: 5.0.4
      hooks:
          - id: flake8
            language: python_venv
            additional_dependencies: [flake8-typing-imports==1.10.0]
