name: Bug report
description: File a bug report to help improve the project
title: '[BUG] '
labels: bug
body:
  - type: markdown
    attributes:
      value: "# Bug report"
  - type: markdown
    attributes:
      value: Thank you for reporting a bug and helping improve Raster Loader!
  - type: markdown
    attributes:
      value: "## Bug description"
  - type: textarea
    id: bug-description
    attributes:
      label: Bug description
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: markdown
    attributes:
      value: "## Expected behavior"
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen
    validations:
      required: true
  - type: markdown
    attributes:
      value: "## Screenshots"
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain the issue.
    validations:
      required: false
  - type: markdown
    attributes:
      value: "## System information"
  - type: textarea
    id: system_info
    attributes:
      label: Environment
      description: >-
        Run `carto info` and paste the output here.
      placeholder: |
        Raster Loader version: 0.1.dev32+gd59b0da
        Python version: 3.11.0 | packaged by conda-forge |
        Platform: Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-glibc2.35
        System version: Linux 5.10.16.3-microsoft-standard-WSL2
        Machine: x86_64
        Processor: x86_64
    validations:
      required: false
  - type: markdown
    attributes:
      value: "## Additional context"
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
    validations:
      required: false
