name: Bug report
description: File a bug report to help improve the project
title: "[BUG] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: "# Bug report"
  - type: markdown
    attributes:
      value: Thank you for reporting a bug and helping improve Raster Loader!
  - type: markdown
    attributes:
      value: "## Bug description"
  - type: textarea
    id: bug-description
    attributes:
      label: Bug description
      description: A clear and concise description of what the bug is.
    validations:
      required: true
