name: Feature request
description: Suggest an idea for this project
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: "# Feature request"
  - type: markdown
    attributes:
      value: Thank you for helping improve Raster Loader!
  - type: markdown
    attributes:
      value: "## Problem description"
  - type: textarea
    id: problem-description
    attributes:
      label: Problem description
      description: A clear and concise description of what the problem is that
      prompted you to think about this new feature.
    validations:
      required: false
  - type: markdown
    attributes:
      value: "## Feature description"
  - type: textarea
    id: feature-description
    attributes:
      label: Feature description
      description: A clear and concise description of the feature you would like
      to see to address the problem outlined above.
    validations:
      required: true
  - type: markdown
    attributes:
      value: "## Alternatives"
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: A clear and concise description of any alternative solutions
      or features you've considered.
    validations:
      required: false
  - type: markdown
    attributes:
      value: "## Additional context"
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false
